-- 012_ebpf_rules_owner.up.sql
-- Distinguish operator-authored rules from auto-generated baseline.
--
-- The `owner` column gates rule lifecycle:
--   - admin (default)  → fully editable; operator created the rule
--   - system           → auto-generated by NexusHub when interfaces
--                        change; operator can toggle is_active but
--                        can't edit fields or delete
--
-- Rationale: the v2.0.0-preview.1 cycle is introducing system-generated
-- cross-location deny rules so a fresh install has a sensible
-- "default-deny between locations" baseline. Operators flip is_active
-- on the pairs they want enforced. Existing rules are grandfathered
-- as owner='admin' via the column default.
--
-- We add a partial index on owner='system' because the regenerator
-- needs to wipe + reinsert that subset on every interface lifecycle
-- event; a full-table scan there would be wasteful at scale.

BEGIN;

ALTER TABLE ebpf_rules
    ADD COLUMN owner TEXT NOT NULL DEFAULT 'admin'
        CHECK (owner IN ('system', 'admin'));

CREATE INDEX idx_ebpf_rules_owner_system ON ebpf_rules (owner)
    WHERE owner = 'system';

COMMIT;
