// Package userspace provides the Go-side loader and map-manager for
// NexusHub's eBPF programs.
//
// The Loader owns an ebpf.Collection (maps + programs) and exposes
// typed CRUD on the blocklist LPM_TRIE maps. Program attach is a
// separate concern handled by callers via the cilium/ebpf link
// package — keeping it out of this type means the Loader is testable
// against maps only (no netns, no kernel interface state).
//
// The Loader is constructed from a *ebpf.CollectionSpec. In
// production, call `loadBlocklist()` (generated by bpf2go) to get
// the spec embedded from the compiled .o; in tests, build a spec
// in-memory. This two-step separates "what the kernel will run" from
// "how we got the bytes".
package userspace

import (
	"errors"
	"fmt"
	"net/netip"

	"github.com/cilium/ebpf"
)

// BlocklistLoader manages the blocklist_v4 and blocklist_v6 LPM_TRIE
// maps. A hit in either map — regardless of value — means the XDP
// program drops the packet.
type BlocklistLoader struct {
	coll *ebpf.Collection

	v4 *ebpf.Map
	v6 *ebpf.Map
}

// Map names in the compiled ELF. These match the variable names in
// ebpf/src/blocklist.c; changing one requires changing the other.
const (
	mapBlocklistV4 = "blocklist_v4"
	mapBlocklistV6 = "blocklist_v6"
)

// NewBlocklistLoader builds the collection from spec, pulls handles
// for the two maps, and returns a ready-to-use loader. The caller
// owns Close() — failing to call it leaks kernel resources.
func NewBlocklistLoader(spec *ebpf.CollectionSpec) (*BlocklistLoader, error) {
	if spec == nil {
		return nil, errors.New("nil spec")
	}
	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		return nil, fmt.Errorf("new collection: %w", err)
	}
	v4, ok := coll.Maps[mapBlocklistV4]
	if !ok {
		coll.Close()
		return nil, fmt.Errorf("map %q missing from spec", mapBlocklistV4)
	}
	v6, ok := coll.Maps[mapBlocklistV6]
	if !ok {
		coll.Close()
		return nil, fmt.Errorf("map %q missing from spec", mapBlocklistV6)
	}
	return &BlocklistLoader{coll: coll, v4: v4, v6: v6}, nil
}

// Close releases every map and program in the underlying collection.
// Safe to call on a nil receiver so `defer loader.Close()` works
// around an early-return constructor failure.
func (l *BlocklistLoader) Close() error {
	if l == nil || l.coll == nil {
		return nil
	}
	l.coll.Close()
	l.coll = nil
	return nil
}

// BlockPrefix adds a CIDR to the blocklist. The value stored is the
// caller-supplied ruleID — looking at the map from a debugger tells
// you which rule row owns the entry, which matters when an operator
// asks "why is this IP dropped?".
//
// Re-adding an existing prefix overwrites the ruleID (BPF_ANY). This
// matches the "DB is source of truth, maps converge" invariant — the
// caller's bookkeeping is always authoritative.
func (l *BlocklistLoader) BlockPrefix(p netip.Prefix, ruleID uint32) error {
	if p.Addr().Is4() {
		k, err := prefixToLPMv4(p)
		if err != nil {
			return err
		}
		return l.v4.Update(k, ruleID, ebpf.UpdateAny)
	}
	k, err := prefixToLPMv6(p)
	if err != nil {
		return err
	}
	return l.v6.Update(k, ruleID, ebpf.UpdateAny)
}

// UnblockPrefix removes a CIDR from the blocklist. Deleting a
// non-existent key returns nil — the end state matches the intent, so
// there's nothing useful the caller can do with an error here.
func (l *BlocklistLoader) UnblockPrefix(p netip.Prefix) error {
	if p.Addr().Is4() {
		k, err := prefixToLPMv4(p)
		if err != nil {
			return err
		}
		return dropENOENT(l.v4.Delete(k))
	}
	k, err := prefixToLPMv6(p)
	if err != nil {
		return err
	}
	return dropENOENT(l.v6.Delete(k))
}

// BlockAddr is the /32 or /128 shortcut for single-host blocks, which
// dominate production load.
func (l *BlocklistLoader) BlockAddr(a netip.Addr, ruleID uint32) error {
	return l.BlockPrefix(netip.PrefixFrom(a, a.BitLen()), ruleID)
}

func (l *BlocklistLoader) UnblockAddr(a netip.Addr) error {
	return l.UnblockPrefix(netip.PrefixFrom(a, a.BitLen()))
}

func dropENOENT(err error) error {
	if err == nil || errors.Is(err, ebpf.ErrKeyNotExist) {
		return nil
	}
	return err
}
