// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package userspace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type RulesLpmV4Key struct {
	Prefixlen uint32
	Addr      [4]uint8
}

type RulesLpmV6Key struct {
	Prefixlen uint32
	Addr      [16]uint8
}

type RulesRateKeyV4 struct {
	RuleId uint32
	Addr   uint32
}

type RulesRateKeyV6 struct {
	RuleId uint32
	Addr   [16]uint8
}

type RulesRateTokens struct {
	TokensX1000 uint64
	LastSeenNs  uint64
}

type RulesRuleHits struct {
	Packets uint64
	Bytes   uint64
}

type RulesRuleMeta struct {
	Action      uint8
	Protocol    uint8
	Direction   uint8
	IsActive    uint8
	SrcPortFrom uint16
	SrcPortTo   uint16
	DstPortFrom uint16
	DstPortTo   uint16
	Priority    uint16
	Pad         uint16
	RatePps     uint32
	RateBurst   uint32
	Pad2        uint32
}

// LoadRules returns the embedded CollectionSpec for Rules.
func LoadRules() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RulesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Rules: %w", err)
	}

	return spec, err
}

// LoadRulesObjects loads Rules and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RulesObjects
//	*RulesPrograms
//	*RulesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRulesObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRules()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RulesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RulesSpecs struct {
	RulesProgramSpecs
	RulesMapSpecs
}

// RulesSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RulesProgramSpecs struct {
	TcRulesWg0 *ebpf.ProgramSpec `ebpf:"tc_rules_wg0"`
	XdpRules   *ebpf.ProgramSpec `ebpf:"xdp_rules"`
}

// RulesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RulesMapSpecs struct {
	LogEvents   *ebpf.MapSpec `ebpf:"log_events"`
	RateStateV4 *ebpf.MapSpec `ebpf:"rate_state_v4"`
	RateStateV6 *ebpf.MapSpec `ebpf:"rate_state_v6"`
	RuleDstV4   *ebpf.MapSpec `ebpf:"rule_dst_v4"`
	RuleDstV6   *ebpf.MapSpec `ebpf:"rule_dst_v6"`
	RuleHits    *ebpf.MapSpec `ebpf:"rule_hits"`
	RuleMeta    *ebpf.MapSpec `ebpf:"rule_meta"`
	RuleSrcV4   *ebpf.MapSpec `ebpf:"rule_src_v4"`
	RuleSrcV6   *ebpf.MapSpec `ebpf:"rule_src_v6"`
}

// RulesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRulesObjects or ebpf.CollectionSpec.LoadAndAssign.
type RulesObjects struct {
	RulesPrograms
	RulesMaps
}

func (o *RulesObjects) Close() error {
	return _RulesClose(
		&o.RulesPrograms,
		&o.RulesMaps,
	)
}

// RulesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRulesObjects or ebpf.CollectionSpec.LoadAndAssign.
type RulesMaps struct {
	LogEvents   *ebpf.Map `ebpf:"log_events"`
	RateStateV4 *ebpf.Map `ebpf:"rate_state_v4"`
	RateStateV6 *ebpf.Map `ebpf:"rate_state_v6"`
	RuleDstV4   *ebpf.Map `ebpf:"rule_dst_v4"`
	RuleDstV6   *ebpf.Map `ebpf:"rule_dst_v6"`
	RuleHits    *ebpf.Map `ebpf:"rule_hits"`
	RuleMeta    *ebpf.Map `ebpf:"rule_meta"`
	RuleSrcV4   *ebpf.Map `ebpf:"rule_src_v4"`
	RuleSrcV6   *ebpf.Map `ebpf:"rule_src_v6"`
}

func (m *RulesMaps) Close() error {
	return _RulesClose(
		m.LogEvents,
		m.RateStateV4,
		m.RateStateV6,
		m.RuleDstV4,
		m.RuleDstV6,
		m.RuleHits,
		m.RuleMeta,
		m.RuleSrcV4,
		m.RuleSrcV6,
	)
}

// RulesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRulesObjects or ebpf.CollectionSpec.LoadAndAssign.
type RulesPrograms struct {
	TcRulesWg0 *ebpf.Program `ebpf:"tc_rules_wg0"`
	XdpRules   *ebpf.Program `ebpf:"xdp_rules"`
}

func (p *RulesPrograms) Close() error {
	return _RulesClose(
		p.TcRulesWg0,
		p.XdpRules,
	)
}

func _RulesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rules_arm64_bpfel.o
var _RulesBytes []byte
