// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package userspace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type RulesRateKeyV4 struct {
	_      structs.HostLayout
	RuleId uint32
	Addr   uint32
}

type RulesRateKeyV6 struct {
	_      structs.HostLayout
	RuleId uint32
	Addr   [16]uint8
}

type RulesRateTokens struct {
	_           structs.HostLayout
	TokensX1000 uint64
	LastSeenNs  uint64
}

type RulesRuleHits struct {
	_       structs.HostLayout
	Packets uint64
	Bytes   uint64
}

type RulesRuleV4Record struct {
	_            structs.HostLayout
	Action       uint8
	Protocol     uint8
	Direction    uint8
	IsActive     uint8
	HasSrc       uint8
	HasDst       uint8
	HasProtocol  uint8
	SrcPrefixLen uint8
	DstPrefixLen uint8
	Pad          [3]uint8
	RatePps      uint32
	RateBurst    uint32
	SrcPortFrom  uint16
	SrcPortTo    uint16
	DstPortFrom  uint16
	DstPortTo    uint16
	Priority     uint16
	Pad2         uint16
	SrcAddr      [4]uint8
	DstAddr      [4]uint8
	RuleId       uint32
}

type RulesRuleV6Record struct {
	_            structs.HostLayout
	Action       uint8
	Protocol     uint8
	Direction    uint8
	IsActive     uint8
	HasSrc       uint8
	HasDst       uint8
	HasProtocol  uint8
	SrcPrefixLen uint8
	DstPrefixLen uint8
	Pad          [3]uint8
	RatePps      uint32
	RateBurst    uint32
	SrcPortFrom  uint16
	SrcPortTo    uint16
	DstPortFrom  uint16
	DstPortTo    uint16
	Priority     uint16
	Pad2         uint16
	SrcAddr      [16]uint8
	DstAddr      [16]uint8
	RuleId       uint32
}

// LoadRules returns the embedded CollectionSpec for Rules.
func LoadRules() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RulesBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Rules: %w", err)
	}

	return spec, err
}

// LoadRulesObjects loads Rules and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RulesObjects
//	*RulesPrograms
//	*RulesMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRulesObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRules()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RulesSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RulesSpecs struct {
	RulesProgramSpecs
	RulesMapSpecs
	RulesVariableSpecs
}

// RulesProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RulesProgramSpecs struct {
	TcRulesWg0 *ebpf.ProgramSpec `ebpf:"tc_rules_wg0"`
	XdpRules   *ebpf.ProgramSpec `ebpf:"xdp_rules"`
}

// RulesMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RulesMapSpecs struct {
	LogEvents   *ebpf.MapSpec `ebpf:"log_events"`
	RateStateV4 *ebpf.MapSpec `ebpf:"rate_state_v4"`
	RateStateV6 *ebpf.MapSpec `ebpf:"rate_state_v6"`
	RuleCountV4 *ebpf.MapSpec `ebpf:"rule_count_v4"`
	RuleCountV6 *ebpf.MapSpec `ebpf:"rule_count_v6"`
	RuleHits    *ebpf.MapSpec `ebpf:"rule_hits"`
	RuleTableV4 *ebpf.MapSpec `ebpf:"rule_table_v4"`
	RuleTableV6 *ebpf.MapSpec `ebpf:"rule_table_v6"`
}

// RulesVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RulesVariableSpecs struct {
}

// RulesObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRulesObjects or ebpf.CollectionSpec.LoadAndAssign.
type RulesObjects struct {
	RulesPrograms
	RulesMaps
	RulesVariables
}

func (o *RulesObjects) Close() error {
	return _RulesClose(
		&o.RulesPrograms,
		&o.RulesMaps,
	)
}

// RulesMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRulesObjects or ebpf.CollectionSpec.LoadAndAssign.
type RulesMaps struct {
	LogEvents   *ebpf.Map `ebpf:"log_events"`
	RateStateV4 *ebpf.Map `ebpf:"rate_state_v4"`
	RateStateV6 *ebpf.Map `ebpf:"rate_state_v6"`
	RuleCountV4 *ebpf.Map `ebpf:"rule_count_v4"`
	RuleCountV6 *ebpf.Map `ebpf:"rule_count_v6"`
	RuleHits    *ebpf.Map `ebpf:"rule_hits"`
	RuleTableV4 *ebpf.Map `ebpf:"rule_table_v4"`
	RuleTableV6 *ebpf.Map `ebpf:"rule_table_v6"`
}

func (m *RulesMaps) Close() error {
	return _RulesClose(
		m.LogEvents,
		m.RateStateV4,
		m.RateStateV6,
		m.RuleCountV4,
		m.RuleCountV6,
		m.RuleHits,
		m.RuleTableV4,
		m.RuleTableV6,
	)
}

// RulesVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRulesObjects or ebpf.CollectionSpec.LoadAndAssign.
type RulesVariables struct {
}

// RulesPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRulesObjects or ebpf.CollectionSpec.LoadAndAssign.
type RulesPrograms struct {
	TcRulesWg0 *ebpf.Program `ebpf:"tc_rules_wg0"`
	XdpRules   *ebpf.Program `ebpf:"xdp_rules"`
}

func (p *RulesPrograms) Close() error {
	return _RulesClose(
		p.TcRulesWg0,
		p.XdpRules,
	)
}

func _RulesClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rules_arm64_bpfel.o
var _RulesBytes []byte
